### ISSUE TITLE
No option to edit images

### ISSUE THREAD

**Issue by glennfeys** [glennfeys/CMSingle#4]
There should be an option where when you click on an image you can choose an image from your filesystem and upload it to the server and edit it like that. But some things here are tricky like what do we do with the old image ? we can't remove it. also if someone tries to use an image multiple times it will be on the server n times, ...

**Comment by ndossche** [comment]
See #5

**Comment by ndossche** [comment]
Ideally, the WYSIWYG editor calls the upload code for you. The rest of this issue is handled by integrating file management I believe.

**Comment by glennfeys** [comment]
can be solved in #15

**Comment by glennfeys** [comment]
this is now added
